## springboot 配置文件

server:
  port: 90
spring:
  application:
    name: cloud-consumer-order90
    # sleuth 服务调用链路跟踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样介于0-1之间。 1标示全部采集
      probability: 1

eureka:
  client:
    service-url: ## 集群版本
      defaultZone:  http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
    fetch-registry: true # 读取eureka列表清单
    register-with-eureka: true #向 eureka 进行注册

