## springboot 配置文件

server:
  port: 90
spring:
  application:
    name: cloud-consumer-fegin-order90

eureka:
  client:
    service-url: ## 集群版本
      defaultZone:  http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
    fetch-registry: true # 读取eureka列表清单
    register-with-eureka: true #向 eureka 进行注册
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 6000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 6000
#日志级别打印
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.yx.springcloud.order.service.PaymentService: debug