server:
  port: 4002
spring:
  application:
    name:  alibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 暴漏端口，供刷新
management:
  endpoints:
    web:
      exposure:
        include: "*"
