server:
  # 9003 表示注册到zookeeper服务器的支付服务提供者端口号
  port: 90
spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-consumer-zk-order90
  cloud:
    zookeeper:
      # 默认localhost:2181
      connect-string: localhost:2181