## springboot 配置文件
## eureka注册中心 服务端
server:
  port: 6002
spring:
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka6002.com
  client:
    register-with-eureka: false # 自己不用注入
    fetch-registry: false # 服务端不用获取清单列表
    service-url:
       defaultZone:  http://eureka6001.com:6001/eureka/
  server: ## 自我保护机制 默认为true  如果90s之内没有响应，就会剔除
    enable-self-preservation: true
